### ISSUE TITLE
change webhook url

### ISSUE THREAD

**Issue by alexis58** [Flolagale/mailin#100]
I want to set webhook url depending on rcptTo address

I'm starting mailin from app.js:

```
mailin.start({
  webhook: 'http://mydomain.com/mailin/incoming,
  disableWebhook: false
});
```

Can I change webhook url smth like this?

```
mailin.on('startMessage', function (connection) {
   if (connection.envelope.rcptTo[0].address == "hook1@domain.com") {
     url = "http://host/ur1.php";
   } else if (connection.envelope.rcptTo[0].address == "hook2@domain.com") {
     url = "http://host/ur2.php";
   }
}
```

Thanks

**Comment by Flolagale** [comment]
No, this won't work if you receive multiple emails simultaneously. However, since you can listen to the `message` event and post the webhook yourself to the correct url. Have a look to the [mailin:postWebhook](https://github.com/Flolagale/mailin/blob/master/lib/mailin.js#L363) method to see how you can do that.

**Comment by alexis58** [comment]
Thank you. Exactly what is needed
